/* Generated By:JavaCC: Do not edit this line. DBParserConstants.java */
package MLNParser.DBParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DBParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 7;
  /** RegularExpression Id. */
  int Variable = 8;
  /** RegularExpression Id. */
  int Constant = 9;
  /** RegularExpression Id. */
  int OpenPar = 10;
  /** RegularExpression Id. */
  int ClosePar = 11;
  /** RegularExpression Id. */
  int Not = 12;
  /** RegularExpression Id. */
  int Unknown = 13;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\",\"",
    "<EOL>",
    "<Variable>",
    "<Constant>",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\"?\"",
  };

}
